spring:
  profiles:
    active: dev
---
server:
  port: 3001
#spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept


---
server:
  port: 3002
#spring的配置
spring:
  profiles: test
  application:
    name: springcloud-provider-dept
